### ISSUE TITLE
Train on MSCOCO dataset

### ISSUE THREAD

**Issue by wangSir0202** [bighuang624/Troika#1]
Dear author， may I have a question that how can I have a train on COCO dataset？

**Comment by bighuang624** [comment]
@wangSir0202 Firstly, the method is only designed for CZSL task, not for detection or segmentation. However, I think you can train a recognition model on a pre-processed COCO dataset, which contains images with state-object compositional labels, if it is neccessary.

**Comment by bighuang624** [comment]
@wangSir0202 I believe the problem has been resolved, so I am closing this issue. Feel free to reopen it if needed.
