### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by hannajiang** [bighuang624/Troika#2]
你好，请问下对于C-GQA数据集，你们是用了一张A100训练的吗，且batchsize设置为16？为什么我在4090上将batchsize设置为1都显示cuda out of memory呀？

**Comment by bighuang624** [comment]
@hannajiang 是的，用的A100。其他参数和开源代码内一致。

**Comment by Lwzzzzzz** [comment]
@hannajiang 请问您后来解决了这个问题吗？

**Comment by Lwzzzzzz** [comment]
@hannajiang 请问你有找到解决这个问题的办法吗？
