### ISSUE TITLE
About val_metric and results

### ISSUE THREAD

**Issue by mjjc111** [bighuang624/Troika#3]
您好。我想问一下您的结果里面有个±多少，这个范围是怎么测量出来的？我的理解是，您的代码里面有个val_metric里面可选的值是"best_seen", "best_unseen", "best_hm", "AUC"，“best_loss”，是把这几个val_metric都跑一遍得到不同的测试结果，这个范围是取所有测试结果里面最大值和最小值？又或是根据您给出的代码.yml文件给出的val_metric直接得到的结果?

**Comment by bighuang624** [comment]
@mjjc111 ± 是标准差。对于我们的方法，我们会使用五个不同的随机种子跑五次随机实验，对于同种指标得到五个结果，计算均值和标准差。

**Comment by mjjc111** [comment]
非常感谢您的回答，我已经明白如何计算结果。我还有一个疑问，对于不同的数据集，指标是如何选取的？

**Comment by bighuang624** [comment]
@mjjc111 没太理解这个“对于不同的数据集，指标是如何选取的”是什么意思？如果你只是说 AUC、HM 这些指标种类的话，每个数据集用的都是同样的一套指标啊，这是 CZSL 任务决定的

**Comment by mjjc111** [comment]
不好意思，是我没表达清楚我的问题。
我想表达的是，在您给出的代码里面，config文件夹的每个数据集的.yml文件里面的val_metric是不同的，mit-states数据集的.yml文件给出的val_metric是best_loss,ut-zappos数据集给出的val_metric是AUC，而cgqa数据集的.yml文件里面val_metric是AUC。
我知道每个数据集都是用同一套指标，每个数据集val_metric可以选取的值有best_loss，best_unseen ，best_seen ，AUC ，best_hm这五种选择，选取的val_metric不同，保存的最优模型权重会不同，最终会影响在测试集上的性能，也就是最终结果会不同。
我想问的是您给出的代码中，config文件夹的每个数据集的.yml文件里面的val_metric是如何来的？就拿mit-states数据集来说，为什么您的mit-states.yml文件里面最终给出的val_metric是best_loss,而不是其他四种？是如何从五种可选的val_metric最终选择best_loss作为mit_states的val_metric的值？数据集选取val_metric最终选取哪一种是根据什么方法确定下来的？
希望我已经表达清楚我的意思，非常感谢您先前的答复，也期待您的再次答复。

**Comment by bighuang624** [comment]
@mjjc111 考虑到 HM 和 AUC 是比较重要的两个指标，因此在单个数据集上根据选择 val_metric 后在 validation set 上 HM 和 AUC 的值人工评估最后确定具体 val_metric。一般优先考虑 AUC 作为默认 val_metric，但是偶尔会发现出现 AUC 高于其他 case 时 HM 反而更低的情况，因此调整一下 val_metric 让二者更加平衡一些。这是我自己实践的一点个人考量，仅供参考。

**Comment by mjjc111** [comment]
明白了，谢谢您的回答，受益匪浅
