### ISSUE TITLE
请问一下，使用C-GQA数据集的时候会导致显存被占满，使用更大的显存也是这样

### ISSUE THREAD

**Issue by siminzheng** [bighuang624/Troika#4]
您好。使用C-GQA数据集的时候会导致现存被占满，我先使用了RTX4090(24GB) 然后使用了V-100(32GB)，但是,发现使用这个数据集时，显存会在一开始训练的时候就被占满，而使用mit-states和ut-zappos数据集时就可以正常训练，我不清楚是否在使用C-GQA数据集之前有什么处理步骤，所以想来请教一下。祝科研顺利

**Comment by Lwzzzzzz** [comment]
请问你有找到解决这个问题的办法吗？

**Comment by bighuang624** [comment]
@Lwzzzzzz C-GQA 数据集的 composition 数量远大于两个数据集，因此在 Troika 方法 forward 中的 cross-modal traction 要显著用更多的显存。我们当时是用 A100 来训练的（不记得具体显存是 40G 还是 80G 了），如果你没有同样的显存条件，又想先在 C-GQA 上把模型跑起来，可以先把 cross-modal traction 部分删掉（`code/model/troika.py` Line 379 - Line 383 做下修改）

**Comment by Lwzzzzzz** [comment]
@bighuang624 感谢解答，但貌似在CLIP编码全部5592个composition时，显存就已经爆了，都到达不了CMT部分。主要的根源在于为了训练CLIP的vocabulary，文本编码器虽然冻住但还是要存中间变量来帮助传播梯度。所以在小显存下，或许只有想办法改成多卡并行，或者混合精度训练，才可能解决这个问题。

CMT的开销反而在OW推理时会比较显著，OW面临的composition数量更大，但由于推理时可以torch.no_grad，所以CLIP这边反而还好，但CMT因为query太多，无法一次性编码成功。我目前通过修改CMT，分批进行qkv，倒是解决了这个问题。
