### ISSUE TITLE
Which A100 gpu is used

### ISSUE THREAD

**Issue by ans92** [bighuang624/Troika#5]
Hi,
Thank you for your work and code. I want to ask, which A100 gpu you have used in your experiments? Is it 40 GB or 80 GB version of A100? Also it is possible to run the model on CGQA dataset on smaller gpu for example V100 32 GB? I have two V100 gpu of 32 GB so would you recommend any method that help me in running the model on CGQA dataset?

**Comment by bighuang624** [comment]
@ans92  I guess it's 80GB version, but I'm not sure as I cannot check my experiment records now. Also, I'm not sure if two V100 gpus of 32 GB can support Troika on CGQA. You can have a try with a smaller batch size, if you think the training is neccessary. Or you can consider deleting the part of cross-modal traction from the code. I'm not quite sure about your purpose, maybe a complete reproduction is not necessary for you.

**Comment by ans92** [comment]
Hi @bighuang624 
Thank you for your reply. I want it as a starting point and do not want to reproduce the results. So do you think by removing cross-modal it will work on CGQA dataset? And how much accuracy will be reduced by removing the cross-modal traction?

**Comment by bighuang624** [comment]
@ans92 
1. I don't know. Just a suggestion as it can help reduce GPU memory burden. Perhaps you can give it a quick try.
2. 1.5% HM and 1.4% AUC drop. Please refer to Table 6 in our paper for more details.

**Comment by bighuang624** [comment]
If there are no more questions, I will close this issue. Feel free to reopen it or start a new issue if needed.

**Comment by ans92** [comment]
Ok. Thank you for your answer.
